language: c

sudo: required

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=luajit2.0  # current head of 2.0 branch
    # - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - sudo apt-get update && sudo apt-get install wget -y
  - .travis/install_es.sh
  - source .travis/setenv_lua.sh
  - luarocks install lunitx
  - luarocks install luacov
  - luarocks install luacov-coveralls

install:
  - luarocks make rockspecs/elasticsearch-lua-1.0.3-1.rockspec

before_script:
  - echo 'elasticsearch version ' && curl http://localhost:9200/
  - curl -XPUT 'localhost:9200/elasticsearch-lua-reindex-index-2'
  - curl -XPUT 'localhost:9200/elasticsearch-lua-reindex-index-1'
  - curl -XPUT 'localhost:9200/elasticsearch-lua-test-index'
  - echo 'Ensure elasticsearch has enough fields configured'
  - "curl -XPUT 'localhost:9200/_settings' -d '{ \"index.mapping.total_fields.limit\": 10000 }' -H 'Content-Type: application/json'"

script:
  - cd tests
  - ./dataset/download-dataset.sh
  - lua run-tests.lua

after_success:  
  - cd ../
  - tests/run-stress-test.sh

notifications:
  email:
    on_success: change
    on_failure: always
